version: 2.1
orbs:
  node: circleci/node@3.0.0

executors:
    node:
      parameters:
        image:
          type: string
          # First 10.x LTS release, but old Yarn
          default: "10.14"
      docker:
        - image: circleci/node:<< parameters.image >>

jobs:
  unit_test:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn test 

workflows:
  test_all:
    jobs:
      - unit_test
