name: cache-deps
description: Creates a cache with the given extension for monorepo dependencies
inputs:
  extension:
    description: Extension for cache name
  force_refresh:
    description: Force refresh the cache (true/false)
    default: 'false'
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{inputs.extension}}-v9-${{ hashFiles('**/yarn.lock', '**/package.json') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{inputs.extension}}-v9-${{ hashFiles('**/yarn.lock') }}-
      # We want to only bootstrap and install if no cache is found.
    - name: Clear yarn cache if forced refresh
      if: inputs.force_refresh == 'true'
      run: rm -rf .yarn/cache
      shell: bash
      
    - run: yarn install --immutable
      shell: bash

    - run: yarn build --no-cache
      shell: bash
