name: GitHub Actions Demo
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'yarn'
          
      - name: assert changed
        run: ./scripts/assert-changed-files.sh "packages/*|(e2e|integration)-tests/*|.circleci/*|yarn.lock"

      - name: install node modules
        run: yarn install --frozen-lockfile
        
      - name: bootstrap
        run: yarn bootstrap --since origin/develop...HEAD --concurrency=2
        
      - run: ./scripts/assert-changed-files.sh "packages"
      
      - name: test
        run: node --max-old-space-size=2048 ./node_modules/.bin/jest -w 1 --changedSince=origin/develop
      
