name: GitHub Actions Demo
on: [push]

jobs:
  bootstrap:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'yarn'
 
      - name: assert changed
        run: ./scripts/assert-changed-files.sh "packages/*|(e2e|integration)-tests/*|.circleci/*|yarn.lock"
 
      - name: Cache node modules
        uses: pat-s/always-upload-cache@v2.1.5
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          
      - name: installation
        run: yarn install
        
      - name: bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn bootstrap --concurrency=2
        
      - name: partial bootstrap
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn bootstrap --since origin/develop...HEAD --concurrency=2
     
      - uses: actions/upload-artifact@v2
        with:
          name: project
          path: .
     

  integration-tests: 
    needs: bootstrap
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: project
      - name: install dev cli
        run: sudo npm i -g medusa-dev-cli
      - name: Set path to medusa repo
        run: medusa-dev --set-path-to-repo `pwd`
      - name: force install
        run: medusa-dev --force-install
        working-directory: integration-tests/api
      - name: install tests
        run: yarn install
        working-directory: integration-tests/api
      - name: build tests
        run: yarn build
        working-directory: integration-tests/api
      - name: integration tests
        run: yarn test
        working-directory: integration-tests/api
        env: 
          DB_USER: postgres
          DB_PASSWORD: postgres
          
  unit-tests:
    needs: bootstrap
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: project
      - name: install node modules
        run: yarn install --frozen-lockfile
      
      - name: test
        run: node --max-old-space-size=2048 ./node_modules/.bin/jest -w 1
      
